### ISSUE TITLE
RangeError: Invalid status code: 0

### ISSUE THREAD

**Issue by philios33** [http-party/node-http-proxy#1080]
Hi

I have no idea how this happens but I am getting this crash dump when I proxy some requests.  It's especially annoying because I can't catch the Exception in my code as it happens in the http-proxy code.  

```
RangeError: Invalid status code: 0
    at ServerResponse.writeHead (_http_server.js:192:11)
    at Array.writeStatusCode (/var/www/node-preview-proxy/node_modules/http-proxy/lib/http-proxy/passes/web-outgoing.js:113:11)
    at ClientRequest.<anonymous> (/var/www/node-preview-proxy/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:157:20)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:472:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
    at Socket.socketOnData (_http_client.js:361:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
```

Could we add some sanity check in here?  I noticed that _http_server.js does this.

```
statusCode |= 0;
  if (statusCode < 100 || statusCode > 999)
    throw new RangeError(`Invalid status code: ${statusCode}`);
```

Using version 1.15.2 of http-proxy

Thanks

**Comment by jcrugzz** [comment]
@philios33 Could you inspect whats coming back from the response by logging on the `proxyRes` event? `proxy.on('proxyRes', function (res) { console.log(res.statusCode) });`

**Comment by Rob--W** [comment]
This can easily be reproduced with the following HTTP response (e.g. via netcat):

```
HTTP/1.0 0
Content-Length: 0

```

**Comment by Rob--W** [comment]
This is a regression, caused by stricter status validation in Node.js (https://github.com/nodejs/node/commit/7e9b0dd6949aaa6afda4da9f41e1d60d9b3d6225) via https://github.com/nodejs/node/pull/6291
