### ISSUE TITLE
TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["set-cookie"]

### ISSUE THREAD

**Issue by SteynMarnus** [http-party/node-http-proxy#1394]
When using Angular 7's functionality to use make use of a proxy, I came across the following error inside of `node-http-proxy` (which is a dependency of Angular):

`TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["set-cookie"]
    at ServerResponse.setHeader (_http_outgoing.js:473:3)
    at setHeader (/Users/marnuss/sc/dpo-payment-page/node_modules/http-proxy/lib/http-proxy/passes/web-outgoing.js:98:15)
    at /Users/marnuss/sc/dpo-payment-page/node_modules/http-proxy/lib/http-proxy/passes/web-outgoing.js:124:7
    at Array.forEach (<anonymous>)
    at Array.writeHeaders (/Users/marnuss/sc/dpo-payment-page/node_modules/http-proxy/lib/http-proxy/passes/web-outgoing.js:119:35)
    at ClientRequest.<anonymous> (/Users/marnuss/sc/dpo-payment-page/node_modules/http-proxy/lib/http-proxy/passes/web-incoming.js:175:22)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at TLSSocket.Readable.push (_stream_readable.js:224:10)
    at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)`

The request I made looked like this :
`this.httpClient.post('API/V6', data, httpOptions)...`
with `httpOptions` being 
`let  httpOptions = {
            headers: new HttpHeaders({
                'content-type': 'application/xml'
            })
        };`

and the proxy setup for my Angular Project looks like this:
`{  
    "/API/V6/*": {  
       "target": "https://secure.3gdirectpay.com/API/V6",  
       "secure": true,  
       "logLevel": "debug",
       "changeOrigin": true
    }  
 } `

**Comment by asbermudez** [comment]
This PR might solve the issue:
https://github.com/http-party/node-http-proxy/pull/1395
