### ISSUE TITLE
body is capped at 10MB with followRedirects=true

### ISSUE THREAD

**Issue by gigafied** [http-party/node-http-proxy#1412]
`follow-redirects` defaults `maxBodyLength` to 10MB.

http-proxy does not expose a way to set any options for this module, what's worse is that the error is actually swallowed silently and the request aborted...

**Comment by ouadakarim** [comment]
Have the same issue. In the past it worked fine, so it seems the `follow-redirects` default settings have been changed. Would be useful if we could set the `maxBodyLength` in the proxy options. At the moment it's not really usable if you're redirecting requests with a body bigger than 10MB.

The error is catchable with the `error` handler:

    proxy.on('error', (err) => console.log(err));

Below the stack trace:

    Error: Request body larger than maxBodyLength limit
    at RedirectableRequest.write (/var/project/node_modules/follow-redirects/index.js:82:24)
    at IncomingMessage.ondata (_stream_readable.js:695:22)
    at IncomingMessage.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at IncomingMessage.Readable.push (_stream_readable.js:209:10)
    at HTTPParser.parserOnBody (_http_common.js:132:24)

**Comment by ouadakarim** [comment]
Created a PR for that https://github.com/http-party/node-http-proxy/pull/1440.

**Comment by blaizard** [comment]
Note, as a workaround, you can always set those values before calling http-proxy 

```
import FollowRedirects from "follow-redirects";
FollowRedirects.maxRedirects = 10;
FollowRedirects.maxBodyLength = 1024 * 1024 * 1024 * 1024;
```
