### ISSUE TITLE
Uncatchable EADDRINUSE error when calling `listen` on occupied port?

### ISSUE THREAD

**Issue by protyposis** [http-party/node-http-proxy#1438]
Please consider this example:

```ts
// A port that is already in use by another process
const occupiedPort = 12345;

const server = httpProxy.createProxyServer({
  target: {
    host: 'localhost',
    port: '8080',
  },
});

server.on('error', error => {
  // No error event
});

try {
  server.listen(occupiedPort);
} catch (error) {
  // No error thrown
}
```

This crashes the Node process with the following error instead of throwing the error from the `listen` method:

```
Error: listen EADDRINUSE: address already in use :::<occupiedPort>
    at Server.setupListenHandle [as _listen2] (net.js:1300:14)
    at listenInCluster (net.js:1348:12)
    at Server.listen (net.js:1436:7)
    at ProxyServer.listen ([...]\node_modules\http-proxy\lib\http-proxy\index.js:136:16)
```

Is there any way to handle this error gracefully?

**Comment by protyposis** [comment]
The problem is that the internal `createServer` and `listen` calls are both done within the same public `listen` method, so there's no way to attach an `error`-event handler before the internal `listen` call:

https://github.com/http-party/node-http-proxy/blob/9bbe486c5efcc356fb4d189ef38eee275bbde345/lib/http-proxy/index.js#L124-L139

Attaching an error-event handler is necessary to overwrite Node's default `EventEmitter.on('error')` behavior - throwing an exception that cannot be caught (the library's internal `ProxyServer.prototype.onError` isn't executed either).

I have temporarily fixed this by monkey patching the `ProxyServer.prototype.listen` to return a `Promise` by replacing

https://github.com/http-party/node-http-proxy/blob/9bbe486c5efcc356fb4d189ef38eee275bbde345/lib/http-proxy/index.js#L136-L138

with 

```ts
  return new Promise((resolve, reject) => {
    const errorHandler = (error: Error) => {
      reject(error);
    };

    // Reject on initial error, e.g. EADDRINUSE
    server.on('error', errorHandler);

    // Resolve when server started successfully
    server.on('listening', () => {
      server.off('error', errorHandler);
      resolve(self);
    });

    server.listen(port, hostname);
  });
```
