### ISSUE TITLE
Examples: <not work>

### ISSUE THREAD

**Issue by brakdag** [http-party/node-http-proxy#1448]
# Examples: <not work>
I try with ***basic_proxy.js***
May be, hard requariments of unnecessary dependences.

I walk in this steps.

```shell
git clone https://github.com/http-party/node-http-proxy.git
npm install
node ./examples/http/basic-proxy.js
```

 its fails, y see in the file basic-proxy require('colors') and require('util'), and then i install it
```shell
npm i -s colors util
```
Next, btw it fails,  

```shell
util.puts(welcome.rainbow.bold);
     ^

TypeError: util.puts is not a function
    at Object.<anonymous> (D:\Lamiwet\proxy\node-http-proxy\examples\http\basic-proxy.js:41:6)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by PierreMage** [comment]
Which version of node are you using? `util.puts` has been deprecated since v0.11.3 and finally removed in v12.x

Extract from [v11.x documentation](https://nodejs.org/docs/latest-v11.x/api/util.html#util_util_puts_strings):
### util.puts([...strings]) 
> Deprecated: Use `console.log()` instead.

**Comment by brakdag** [comment]
I'm not using utils.puts
sorry, the code of your exampes uses utls.puts

**Comment by PierreMage** [comment]
The example [`basic_proxy.js`](https://github.com/http-party/node-http-proxy/blob/master/examples/http/basic-proxy.js#L41) uses `util.puts`.

Couldn't find `util.puts` in [node-util](https://github.com/browserify/node-util/search?q=puts&unscoped_q=puts), the one installed by `npm i -s util`. So that wouldn't fix the error `TypeError: util.puts is not a function`.

The PR, [Fix examples for node v12.x](https://github.com/http-party/node-http-proxy/pull/1452/files#diff-9cc72b838b00018f763cb842b61302d5), should fix the error when merged. In the meantime you can manually edit the file and replace `util.puts` with `console.log`.

**Comment by brakdag** [comment]
Ahh, ok, thanks

**Comment by asheroto** [comment]
[reverse-proxy.js](https://github.com/http-party/node-http-proxy/blob/master/examples/http/reverse-proxy.js#L33-L40) has it too
